### ISSUE TITLE
cannot support create items from non-journal pages？

### ISSUE THREAD

**Issue by zhoulukuan** [hkgnp/logseq-trackhabits2-plugin#6]
When I try to create a loop from a non-journal page, the content stays at the last one created in the journal, so this plugin cannot support create items from non-journal pages?

**Comment by benjypng** [comment]
Hi, yes that is correct because it uses the date that the TODO is on to check if the habit has been done. Regards,ben On 1 Dec 2022, at 1:57 AM, lity ***@***.***> wrote:﻿
When I try to create a loop from a non-journal page, the content stays at the last one created in the journal, so this plugin cannot support create items from non-journal pages?
